script_template: inno_setup.iss
# AppId 的值唯一标识此应用。
# 不要在其他应用的安装程序中使用相同的 AppId 值。
app_id: c7a42e18-6d8b-4b2e-a5a1-9b7e3f28d8a1
publisher: xin-build
publisher_url: https://github.com/xin-build/PiliPlus-A
display_name: PiliPlus-A
# create_desktop_icon: true
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_defaultdirname
install_dir_name: "{autopf}\\PiliPlus-A"
# 这里的路径是相对于项目根目录的路径； 图标格式必须是ico格式，不能是png或其它
setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - en
  - zh
privileges_required: admin
