//
//  Generated by manual porting of bilibili.app.playerunite.v1.PlayViewUnite
//
// @dart = 3.3

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:core' as $core;

import 'package:fixnum/fixnum.dart' as $fixnum;
import 'package:protobuf/protobuf.dart' as $pb;

import 'package:PiliPlus/grpc/bilibili/playershared.pb.dart' as $shared;

class PlayViewUniteReq extends $pb.GeneratedMessage {
  factory PlayViewUniteReq({
    $shared.VideoVod? vod,
    $core.String? spmid,
    $core.String? fromSpmid,
    $shared.PlayCtrl? playCtrl,
    $core.String? fromScene,
    $core.String? adExtra,
    $core.Iterable<$core.MapEntry<$core.String, $core.String>>? extraContent,
  }) {
    final result = create();
    if (vod != null) result.vod = vod;
    if (spmid != null) result.spmid = spmid;
    if (fromSpmid != null) result.fromSpmid = fromSpmid;
    if (playCtrl != null) result.playCtrl = playCtrl;
    if (fromScene != null) result.fromScene = fromScene;
    if (adExtra != null) result.adExtra = adExtra;
    if (extraContent != null) result.extraContent.addEntries(extraContent);
    return result;
  }

  PlayViewUniteReq._();

  factory PlayViewUniteReq.fromBuffer($core.List<$core.int> data,
          [$pb.ExtensionRegistry registry = $pb.ExtensionRegistry.EMPTY]) =>
      create()..mergeFromBuffer(data, registry);
  factory PlayViewUniteReq.fromJson($core.String json,
          [$pb.ExtensionRegistry registry = $pb.ExtensionRegistry.EMPTY]) =>
      create()..mergeFromJson(json, registry);

  static final $pb.BuilderInfo _i = $pb.BuilderInfo(
      'PlayViewUniteReq',
      package: const $pb.PackageName('bilibili.app.playerunite.v1'),
      createEmptyInstance: create)
    ..aOM<$shared.VideoVod>(1, 'vod', subBuilder: $shared.VideoVod.create)
    ..aOS(2, 'spmid')
    ..aOS(3, 'fromSpmid')
    ..aE<$shared.PlayCtrl>(4, 'playCtrl', enumValues: $shared.PlayCtrl.values)
    ..aOS(5, 'fromScene')
    ..aOS(6, 'adExtra')
    ..m<$core.String, $core.String>(7, 'extraContent',
        entryClassName: 'PlayViewUniteReq.ExtraContentEntry',
        keyFieldType: $pb.PbFieldType.OS,
        valueFieldType: $pb.PbFieldType.OS,
        packageName: const $pb.PackageName('bilibili.app.playerunite.v1'))
    ..hasRequiredFields = false;

  @$core.Deprecated('See https://github.com/google/protobuf.dart/issues/998.')
  PlayViewUniteReq clone() => deepCopy();
  @$core.Deprecated('See https://github.com/google/protobuf.dart/issues/998.')
  PlayViewUniteReq copyWith(void Function(PlayViewUniteReq) updates) =>
      super.copyWith((message) => updates(message as PlayViewUniteReq))
          as PlayViewUniteReq;

  @$core.override
  $pb.BuilderInfo get info_ => _i;

  @$core.pragma('dart2js:noInline')
  static PlayViewUniteReq create() => PlayViewUniteReq._();
  @$core.override
  PlayViewUniteReq createEmptyInstance() => create();
  @$core.pragma('dart2js:noInline')
  static PlayViewUniteReq getDefault() =>
      _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<PlayViewUniteReq>(create);
  static PlayViewUniteReq? _defaultInstance;

  @$pb.TagNumber(1)
  $shared.VideoVod get vod => $_getN(0);
  @$pb.TagNumber(1)
  set vod($shared.VideoVod value) => $_setField(1, value);
  @$pb.TagNumber(1)
  $core.bool hasVod() => $_has(0);
  @$pb.TagNumber(1)
  void clearVod() => $_clearField(1);
  @$pb.TagNumber(1)
  $shared.VideoVod ensureVod() => $_ensure(0);

  @$pb.TagNumber(2)
  $core.String get spmid => $_getSZ(1);
  @$pb.TagNumber(2)
  set spmid($core.String value) => $_setString(1, value);
  @$pb.TagNumber(2)
  $core.bool hasSpmid() => $_has(1);
  @$pb.TagNumber(2)
  void clearSpmid() => $_clearField(2);

  @$pb.TagNumber(3)
  $core.String get fromSpmid => $_getSZ(2);
  @$pb.TagNumber(3)
  set fromSpmid($core.String value) => $_setString(2, value);
  @$pb.TagNumber(3)
  $core.bool hasFromSpmid() => $_has(2);
  @$pb.TagNumber(3)
  void clearFromSpmid() => $_clearField(3);

  @$pb.TagNumber(4)
  $shared.PlayCtrl get playCtrl => $_getN(3);
  @$pb.TagNumber(4)
  set playCtrl($shared.PlayCtrl value) => $_setField(4, value);
  @$pb.TagNumber(4)
  $core.bool hasPlayCtrl() => $_has(3);
  @$pb.TagNumber(4)
  void clearPlayCtrl() => $_clearField(4);

  @$pb.TagNumber(5)
  $core.String get fromScene => $_getSZ(4);
  @$pb.TagNumber(5)
  set fromScene($core.String value) => $_setString(4, value);
  @$pb.TagNumber(5)
  $core.bool hasFromScene() => $_has(4);
  @$pb.TagNumber(5)
  void clearFromScene() => $_clearField(5);

  @$pb.TagNumber(6)
  $core.String get adExtra => $_getSZ(5);
  @$pb.TagNumber(6)
  set adExtra($core.String value) => $_setString(5, value);
  @$pb.TagNumber(6)
  $core.bool hasAdExtra() => $_has(5);
  @$pb.TagNumber(6)
  void clearAdExtra() => $_clearField(6);

  @$pb.TagNumber(7)
  $core.Map<$core.String, $core.String> get extraContent => $_getMap(6);
}

class PlayViewUniteReply extends $pb.GeneratedMessage {
  factory PlayViewUniteReply({
    $shared.VodInfo? vodInfo,
    $shared.QnTrialInfo? qnTrialInfo,
  }) {
    final result = create();
    if (vodInfo != null) result.vodInfo = vodInfo;
    if (qnTrialInfo != null) result.qnTrialInfo = qnTrialInfo;
    return result;
  }

  PlayViewUniteReply._();

  factory PlayViewUniteReply.fromBuffer($core.List<$core.int> data,
          [$pb.ExtensionRegistry registry = $pb.ExtensionRegistry.EMPTY]) =>
      create()..mergeFromBuffer(data, registry);
  factory PlayViewUniteReply.fromJson($core.String json,
          [$pb.ExtensionRegistry registry = $pb.ExtensionRegistry.EMPTY]) =>
      create()..mergeFromJson(json, registry);

  static final $pb.BuilderInfo _i = $pb.BuilderInfo(
      'PlayViewUniteReply',
      package: const $pb.PackageName('bilibili.app.playerunite.v1'),
      createEmptyInstance: create)
    ..aOM<$shared.VodInfo>(1, 'vodInfo', subBuilder: $shared.VodInfo.create)
    ..aOM<$shared.QnTrialInfo>(3, 'qnTrialInfo', subBuilder: $shared.QnTrialInfo.create)
    ..hasRequiredFields = false;

  @$core.Deprecated('See https://github.com/google/protobuf.dart/issues/998.')
  PlayViewUniteReply clone() => deepCopy();
  @$core.Deprecated('See https://github.com/google/protobuf.dart/issues/998.')
  PlayViewUniteReply copyWith(void Function(PlayViewUniteReply) updates) =>
      super.copyWith((message) => updates(message as PlayViewUniteReply))
          as PlayViewUniteReply;

  @$core.override
  $pb.BuilderInfo get info_ => _i;

  @$core.pragma('dart2js:noInline')
  static PlayViewUniteReply create() => PlayViewUniteReply._();
  @$core.override
  PlayViewUniteReply createEmptyInstance() => create();
  @$core.pragma('dart2js:noInline')
  static PlayViewUniteReply getDefault() =>
      _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<PlayViewUniteReply>(create);
  static PlayViewUniteReply? _defaultInstance;

  @$pb.TagNumber(1)
  $shared.VodInfo get vodInfo => $_getN(0);
  @$pb.TagNumber(1)
  set vodInfo($shared.VodInfo value) => $_setField(1, value);
  @$pb.TagNumber(1)
  $core.bool hasVodInfo() => $_has(0);
  @$pb.TagNumber(1)
  void clearVodInfo() => $_clearField(1);
  @$pb.TagNumber(1)
  $shared.VodInfo ensureVodInfo() => $_ensure(0);

  @$pb.TagNumber(3)
  $shared.QnTrialInfo get qnTrialInfo => $_getN(1);
  @$pb.TagNumber(3)
  set qnTrialInfo($shared.QnTrialInfo value) => $_setField(3, value);
  @$pb.TagNumber(3)
  $core.bool hasQnTrialInfo() => $_has(1);
  @$pb.TagNumber(3)
  void clearQnTrialInfo() => $_clearField(3);
  @$pb.TagNumber(3)
  $shared.QnTrialInfo ensureQnTrialInfo() => $_ensure(1);
}
