name: Build for Mac

on:
  workflow_call:
    inputs:
      tag:
        description: "tag"
        required: false
        default: ""
        type: string
  workflow_dispatch:

jobs:
  build-mac-app:
    name: Release Mac
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Set and Extract version
        shell: pwsh
        run: lib/scripts/build.ps1

      - name: Apply Patch
        shell: pwsh
        run: lib/scripts/patch.ps1 macOS
        continue-on-error: true

      - name: Build Mac
        run: flutter build macos --release --dart-define-from-file=pili_release.json --no-pub

      - name: Prepare Upload
        run: |
          npm install --global create-dmg || true
          create-dmg build/macos/Build/Products/Release/PiliPlus.app || true
          if ! ls PiliPlus*.dmg 1> /dev/null 2>&1; then
            echo "Fallback to hdiutil create..."
            hdiutil create -volname "PiliPlus" -srcfolder "build/macos/Build/Products/Release/PiliPlus.app" -ov -format UDZO "PiliPlus_macos_${{ env.version }}.dmg" || true
          else
            mv PiliPlus*.dmg "PiliPlus_macos_${{ env.version }}.dmg" || true
          fi
          ditto -c -k --sequesterRsrc --keepParent "build/macos/Build/Products/Release/PiliPlus.app" "PiliPlus_macos_${{ env.version }}.zip" || true
        shell: bash

      - name: Release
        if: ${{ inputs.tag != '' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name: ${{ inputs.tag }}
          files: |
            PiliPlus_macos_*.dmg
            PiliPlus_macos_*.zip

      - name: Upload macos release
        uses: actions/upload-artifact@v4
        with:
          name: macOS-release
          path: |
            PiliPlus_macos_*.dmg
            PiliPlus_macos_*.zip
          if-no-files-found: warn
